### ISSUE TITLE
Bug with clicked pins 

### ISSUE THREAD

**Issue by Verbavolant2023** [ali7ali/Alpha-Google-Map-For-Elementor#1]
Hi,
there is a bug when i click a pin on the map sometimes changes the images of other pins
Example: 
Pin 1 has image 1
Pin 2 has image 2
I click Pin 1, Pin 2 change to image 1
Than i click Pin 2 and the image return to image 2 but also Pin 1 change image to image 2

**Comment by ali7ali** [comment]
Hello @Verbavolant2023 
Thank you for reporting this, I can replicate it, it will be resolved in version 1.0.9

**Comment by Verbavolant2023** [comment]
Thank you! This plug in is super useful!

**Comment by ali7ali** [comment]
Sorry @Verbavolant2023  it was a busy couple of weeks! Glad to know that!
V1.0.9 is released.
Please let me know if this issue is resolved.

**Comment by Verbavolant2023** [comment]
Yes the issue is resolved, thanks a lot!
