### ISSUE TITLE
Alpha Google Map For Elementor requires "Elementor" on the last elementor version

### ISSUE THREAD

**Issue by Bitrate2001** [ali7ali/Alpha-Google-Map-For-Elementor#2]
Hi, 
On the last version of elementor I get this error "Alpha Google Map For Elementor requires "Elementor" plugin to be active. Please activate Elementor to continue." Can you solve ?
Thanks a lot.

**Comment by ali7ali** [comment]
Hey @Bitrate2001 
Thank you for reporting this issue, it's now resolved with v1.2.0
Please reopen this issue if needed or start a new one if unrelated.
